apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "smokeping-prober.fullname" . }}
  labels:
    {{- include "smokeping-prober.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "smokeping-prober.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "smokeping-prober.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "smokeping-prober.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- if .Values.config.web.listenAddress }}
            - {{ printf "%s=:%d" "--web.listen-address" (int .Values.config.web.listenAddress) | quote }}
            {{- end }}
            {{- if .Values.config.web.telemetryPath }}
            - {{ printf "%s=%s" "--web.telemetry-path" .Values.config.web.telemetryPath | quote }}
            {{- end }}
            {{- if .Values.config.buckets }}
            - {{ printf "%s=%s" "--buckets" (join "," .Values.config.buckets) | quote }}
            {{- end }}
            {{- if .Values.config.ping.interval }}
            - {{ printf "%s=%s" "--ping.interval" .Values.config.ping.interval | quote }}
            {{- end }}
            {{- if .Values.config.privileged }}
            - "--privileged"
            {{- end }}
            {{- if .Values.config.log.level }}
            - {{ printf "%s=%s" "--log.level" .Values.config.log.level | quote }}
            {{- end }}
            {{- if .Values.config.log.format }}
            - {{ printf "%s=%s" "--log.format" .Values.config.log.format | quote }}
            {{- end }}
            {{- if .Values.config.extraArgs }}
            {{- range .Values.config.extraArgs }}
            - {{ . | quote }}
            {{- end }}
            {{- end }}
            {{- range .Values.config.hosts }}
            - {{ . | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.config.web.listenAddress }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
