apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "smokeping-prober.fullname" . }}
  labels:
    {{- include "smokeping-prober.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "smokeping-prober.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
